version: '3.8'

services:
  app:
    image: 'docker-springboot-postgres:latest'
    build:
      context: .
    container_name: app
    environment:
      - POSTGRES_USER=nexusbuilder
      - POSTGRES_PASSWORD=EasyFood123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://easyfoodbd.postgres.database.azure.com/EasyFood
      - SPRING_DATASOURCE_USERNAME=nexusbuilder
      - SPRING_DATASOURCE_PASSWORD=EasyFood123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "80:8080"


  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=nexusbuilder
      - POSTGRES_PASSWORD=EasyFood123
      - POSTGRES_DB=EasyFood
    ports:
      - "5432:5432"
